[functions.send-application-notification]
verify_jwt = false

[functions.notify-gallery-open]
verify_jwt = false

[functions.send-team-request-notification]
verify_jwt = false

[functions.notify-organizer-application]
verify_jwt = false

project_id = "ficvvbulwubskqghzbkk"
